defaultBaseImage: alpine

builds:
- id: frpp
  # env:
  # - GOCACHE=/.gocache
  ldflags:
  - -s -w
  - -X github.com/VaalaCat/frp-panel/conf.buildDate={{.Date}}
  - -X github.com/VaalaCat/frp-panel/conf.gitCommit={{.Git.FullCommit}}
  - -X github.com/VaalaCat/frp-panel/conf.gitVersion={{.Git.Tag}}
  - -X github.com/VaalaCat/frp-panel/conf.gitBranch={{.Git.Branch}}

defaultPlatforms:
- linux/arm64
- linux/amd64