// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api_client.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      *string                `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	Ephemeral     *bool                  `protobuf:"varint,2,opt,name=ephemeral,proto3,oneof" json:"ephemeral,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitClientRequest) Reset() {
	*x = InitClientRequest{}
	mi := &file_api_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitClientRequest) ProtoMessage() {}

func (x *InitClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitClientRequest.ProtoReflect.Descriptor instead.
func (*InitClientRequest) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{0}
}

func (x *InitClientRequest) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *InitClientRequest) GetEphemeral() bool {
	if x != nil && x.Ephemeral != nil {
		return *x.Ephemeral
	}
	return false
}

type InitClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	ClientId      *string                `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitClientResponse) Reset() {
	*x = InitClientResponse{}
	mi := &file_api_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitClientResponse) ProtoMessage() {}

func (x *InitClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitClientResponse.ProtoReflect.Descriptor instead.
func (*InitClientResponse) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{1}
}

func (x *InitClientResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *InitClientResponse) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

type ListClientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *int32                 `protobuf:"varint,1,opt,name=page,proto3,oneof" json:"page,omitempty"`
	PageSize      *int32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	Keyword       *string                `protobuf:"bytes,3,opt,name=keyword,proto3,oneof" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientsRequest) Reset() {
	*x = ListClientsRequest{}
	mi := &file_api_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientsRequest) ProtoMessage() {}

func (x *ListClientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientsRequest.ProtoReflect.Descriptor instead.
func (*ListClientsRequest) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{2}
}

func (x *ListClientsRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListClientsRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListClientsRequest) GetKeyword() string {
	if x != nil && x.Keyword != nil {
		return *x.Keyword
	}
	return ""
}

type ListClientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Total         *int32                 `protobuf:"varint,2,opt,name=total,proto3,oneof" json:"total,omitempty"`
	Clients       []*Client              `protobuf:"bytes,3,rep,name=clients,proto3" json:"clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientsResponse) Reset() {
	*x = ListClientsResponse{}
	mi := &file_api_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientsResponse) ProtoMessage() {}

func (x *ListClientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientsResponse.ProtoReflect.Descriptor instead.
func (*ListClientsResponse) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{3}
}

func (x *ListClientsResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListClientsResponse) GetTotal() int32 {
	if x != nil && x.Total != nil {
		return *x.Total
	}
	return 0
}

func (x *ListClientsResponse) GetClients() []*Client {
	if x != nil {
		return x.Clients
	}
	return nil
}

type GetClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      *string                `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	ServerId      *string                `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3,oneof" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientRequest) Reset() {
	*x = GetClientRequest{}
	mi := &file_api_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientRequest) ProtoMessage() {}

func (x *GetClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientRequest.ProtoReflect.Descriptor instead.
func (*GetClientRequest) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{4}
}

func (x *GetClientRequest) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *GetClientRequest) GetServerId() string {
	if x != nil && x.ServerId != nil {
		return *x.ServerId
	}
	return ""
}

type GetClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Client        *Client                `protobuf:"bytes,2,opt,name=client,proto3,oneof" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientResponse) Reset() {
	*x = GetClientResponse{}
	mi := &file_api_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientResponse) ProtoMessage() {}

func (x *GetClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientResponse.ProtoReflect.Descriptor instead.
func (*GetClientResponse) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{5}
}

func (x *GetClientResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetClientResponse) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

type DeleteClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      *string                `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClientRequest) Reset() {
	*x = DeleteClientRequest{}
	mi := &file_api_client_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClientRequest) ProtoMessage() {}

func (x *DeleteClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClientRequest.ProtoReflect.Descriptor instead.
func (*DeleteClientRequest) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteClientRequest) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

type DeleteClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClientResponse) Reset() {
	*x = DeleteClientResponse{}
	mi := &file_api_client_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClientResponse) ProtoMessage() {}

func (x *DeleteClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClientResponse.ProtoReflect.Descriptor instead.
func (*DeleteClientResponse) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteClientResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type UpdateFRPCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      *string                `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	ServerId      *string                `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3,oneof" json:"server_id,omitempty"`
	Config        []byte                 `protobuf:"bytes,3,opt,name=config,proto3,oneof" json:"config,omitempty"`
	Comment       *string                `protobuf:"bytes,4,opt,name=comment,proto3,oneof" json:"comment,omitempty"`
	FrpsUrl       *string                `protobuf:"bytes,5,opt,name=frps_url,json=frpsUrl,proto3,oneof" json:"frps_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFRPCRequest) Reset() {
	*x = UpdateFRPCRequest{}
	mi := &file_api_client_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFRPCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFRPCRequest) ProtoMessage() {}

func (x *UpdateFRPCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFRPCRequest.ProtoReflect.Descriptor instead.
func (*UpdateFRPCRequest) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateFRPCRequest) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *UpdateFRPCRequest) GetServerId() string {
	if x != nil && x.ServerId != nil {
		return *x.ServerId
	}
	return ""
}

func (x *UpdateFRPCRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *UpdateFRPCRequest) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

func (x *UpdateFRPCRequest) GetFrpsUrl() string {
	if x != nil && x.FrpsUrl != nil {
		return *x.FrpsUrl
	}
	return ""
}

type UpdateFRPCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFRPCResponse) Reset() {
	*x = UpdateFRPCResponse{}
	mi := &file_api_client_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFRPCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFRPCResponse) ProtoMessage() {}

func (x *UpdateFRPCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFRPCResponse.ProtoReflect.Descriptor instead.
func (*UpdateFRPCResponse) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateFRPCResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type RemoveFRPCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      *string                `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFRPCRequest) Reset() {
	*x = RemoveFRPCRequest{}
	mi := &file_api_client_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFRPCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFRPCRequest) ProtoMessage() {}

func (x *RemoveFRPCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFRPCRequest.ProtoReflect.Descriptor instead.
func (*RemoveFRPCRequest) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveFRPCRequest) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

type RemoveFRPCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFRPCResponse) Reset() {
	*x = RemoveFRPCResponse{}
	mi := &file_api_client_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFRPCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFRPCResponse) ProtoMessage() {}

func (x *RemoveFRPCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFRPCResponse.ProtoReflect.Descriptor instead.
func (*RemoveFRPCResponse) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveFRPCResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type StopFRPCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      *string                `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopFRPCRequest) Reset() {
	*x = StopFRPCRequest{}
	mi := &file_api_client_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopFRPCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopFRPCRequest) ProtoMessage() {}

func (x *StopFRPCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopFRPCRequest.ProtoReflect.Descriptor instead.
func (*StopFRPCRequest) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{12}
}

func (x *StopFRPCRequest) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

type StopFRPCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopFRPCResponse) Reset() {
	*x = StopFRPCResponse{}
	mi := &file_api_client_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopFRPCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopFRPCResponse) ProtoMessage() {}

func (x *StopFRPCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopFRPCResponse.ProtoReflect.Descriptor instead.
func (*StopFRPCResponse) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{13}
}

func (x *StopFRPCResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type StartFRPCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      *string                `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartFRPCRequest) Reset() {
	*x = StartFRPCRequest{}
	mi := &file_api_client_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartFRPCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartFRPCRequest) ProtoMessage() {}

func (x *StartFRPCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartFRPCRequest.ProtoReflect.Descriptor instead.
func (*StartFRPCRequest) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{14}
}

func (x *StartFRPCRequest) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

type StartFRPCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartFRPCResponse) Reset() {
	*x = StartFRPCResponse{}
	mi := &file_api_client_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartFRPCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartFRPCResponse) ProtoMessage() {}

func (x *StartFRPCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartFRPCResponse.ProtoReflect.Descriptor instead.
func (*StartFRPCResponse) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{15}
}

func (x *StartFRPCResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetProxyStatsByClientIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      *string                `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProxyStatsByClientIDRequest) Reset() {
	*x = GetProxyStatsByClientIDRequest{}
	mi := &file_api_client_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProxyStatsByClientIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProxyStatsByClientIDRequest) ProtoMessage() {}

func (x *GetProxyStatsByClientIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProxyStatsByClientIDRequest.ProtoReflect.Descriptor instead.
func (*GetProxyStatsByClientIDRequest) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{16}
}

func (x *GetProxyStatsByClientIDRequest) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

type GetProxyStatsByClientIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	ProxyInfos    []*ProxyInfo           `protobuf:"bytes,2,rep,name=proxy_infos,json=proxyInfos,proto3" json:"proxy_infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProxyStatsByClientIDResponse) Reset() {
	*x = GetProxyStatsByClientIDResponse{}
	mi := &file_api_client_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProxyStatsByClientIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProxyStatsByClientIDResponse) ProtoMessage() {}

func (x *GetProxyStatsByClientIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProxyStatsByClientIDResponse.ProtoReflect.Descriptor instead.
func (*GetProxyStatsByClientIDResponse) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{17}
}

func (x *GetProxyStatsByClientIDResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetProxyStatsByClientIDResponse) GetProxyInfos() []*ProxyInfo {
	if x != nil {
		return x.ProxyInfos
	}
	return nil
}

type ListProxyConfigsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *int32                 `protobuf:"varint,1,opt,name=page,proto3,oneof" json:"page,omitempty"`
	PageSize      *int32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	Keyword       *string                `protobuf:"bytes,3,opt,name=keyword,proto3,oneof" json:"keyword,omitempty"`
	ClientId      *string                `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	ServerId      *string                `protobuf:"bytes,5,opt,name=server_id,json=serverId,proto3,oneof" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProxyConfigsRequest) Reset() {
	*x = ListProxyConfigsRequest{}
	mi := &file_api_client_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProxyConfigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProxyConfigsRequest) ProtoMessage() {}

func (x *ListProxyConfigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProxyConfigsRequest.ProtoReflect.Descriptor instead.
func (*ListProxyConfigsRequest) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{18}
}

func (x *ListProxyConfigsRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListProxyConfigsRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListProxyConfigsRequest) GetKeyword() string {
	if x != nil && x.Keyword != nil {
		return *x.Keyword
	}
	return ""
}

func (x *ListProxyConfigsRequest) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *ListProxyConfigsRequest) GetServerId() string {
	if x != nil && x.ServerId != nil {
		return *x.ServerId
	}
	return ""
}

type ListProxyConfigsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Total         *int32                 `protobuf:"varint,2,opt,name=total,proto3,oneof" json:"total,omitempty"`
	ProxyConfigs  []*ProxyConfig         `protobuf:"bytes,3,rep,name=proxy_configs,json=proxyConfigs,proto3" json:"proxy_configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProxyConfigsResponse) Reset() {
	*x = ListProxyConfigsResponse{}
	mi := &file_api_client_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProxyConfigsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProxyConfigsResponse) ProtoMessage() {}

func (x *ListProxyConfigsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProxyConfigsResponse.ProtoReflect.Descriptor instead.
func (*ListProxyConfigsResponse) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{19}
}

func (x *ListProxyConfigsResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListProxyConfigsResponse) GetTotal() int32 {
	if x != nil && x.Total != nil {
		return *x.Total
	}
	return 0
}

func (x *ListProxyConfigsResponse) GetProxyConfigs() []*ProxyConfig {
	if x != nil {
		return x.ProxyConfigs
	}
	return nil
}

type CreateProxyConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      *string                `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	ServerId      *string                `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3,oneof" json:"server_id,omitempty"`
	Config        []byte                 `protobuf:"bytes,3,opt,name=config,proto3,oneof" json:"config,omitempty"`
	Overwrite     *bool                  `protobuf:"varint,4,opt,name=overwrite,proto3,oneof" json:"overwrite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProxyConfigRequest) Reset() {
	*x = CreateProxyConfigRequest{}
	mi := &file_api_client_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProxyConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProxyConfigRequest) ProtoMessage() {}

func (x *CreateProxyConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProxyConfigRequest.ProtoReflect.Descriptor instead.
func (*CreateProxyConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{20}
}

func (x *CreateProxyConfigRequest) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *CreateProxyConfigRequest) GetServerId() string {
	if x != nil && x.ServerId != nil {
		return *x.ServerId
	}
	return ""
}

func (x *CreateProxyConfigRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreateProxyConfigRequest) GetOverwrite() bool {
	if x != nil && x.Overwrite != nil {
		return *x.Overwrite
	}
	return false
}

type CreateProxyConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProxyConfigResponse) Reset() {
	*x = CreateProxyConfigResponse{}
	mi := &file_api_client_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProxyConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProxyConfigResponse) ProtoMessage() {}

func (x *CreateProxyConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProxyConfigResponse.ProtoReflect.Descriptor instead.
func (*CreateProxyConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{21}
}

func (x *CreateProxyConfigResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type DeleteProxyConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      *string                `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	ServerId      *string                `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3,oneof" json:"server_id,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProxyConfigRequest) Reset() {
	*x = DeleteProxyConfigRequest{}
	mi := &file_api_client_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProxyConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProxyConfigRequest) ProtoMessage() {}

func (x *DeleteProxyConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProxyConfigRequest.ProtoReflect.Descriptor instead.
func (*DeleteProxyConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteProxyConfigRequest) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *DeleteProxyConfigRequest) GetServerId() string {
	if x != nil && x.ServerId != nil {
		return *x.ServerId
	}
	return ""
}

func (x *DeleteProxyConfigRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type DeleteProxyConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProxyConfigResponse) Reset() {
	*x = DeleteProxyConfigResponse{}
	mi := &file_api_client_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProxyConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProxyConfigResponse) ProtoMessage() {}

func (x *DeleteProxyConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProxyConfigResponse.ProtoReflect.Descriptor instead.
func (*DeleteProxyConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteProxyConfigResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type UpdateProxyConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      *string                `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	ServerId      *string                `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3,oneof" json:"server_id,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Config        []byte                 `protobuf:"bytes,4,opt,name=config,proto3,oneof" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProxyConfigRequest) Reset() {
	*x = UpdateProxyConfigRequest{}
	mi := &file_api_client_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProxyConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProxyConfigRequest) ProtoMessage() {}

func (x *UpdateProxyConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProxyConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateProxyConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateProxyConfigRequest) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *UpdateProxyConfigRequest) GetServerId() string {
	if x != nil && x.ServerId != nil {
		return *x.ServerId
	}
	return ""
}

func (x *UpdateProxyConfigRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateProxyConfigRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateProxyConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProxyConfigResponse) Reset() {
	*x = UpdateProxyConfigResponse{}
	mi := &file_api_client_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProxyConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProxyConfigResponse) ProtoMessage() {}

func (x *UpdateProxyConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProxyConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateProxyConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateProxyConfigResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetProxyConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      *string                `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	ServerId      *string                `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3,oneof" json:"server_id,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProxyConfigRequest) Reset() {
	*x = GetProxyConfigRequest{}
	mi := &file_api_client_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProxyConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProxyConfigRequest) ProtoMessage() {}

func (x *GetProxyConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProxyConfigRequest.ProtoReflect.Descriptor instead.
func (*GetProxyConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{26}
}

func (x *GetProxyConfigRequest) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *GetProxyConfigRequest) GetServerId() string {
	if x != nil && x.ServerId != nil {
		return *x.ServerId
	}
	return ""
}

func (x *GetProxyConfigRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type GetProxyConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	ProxyConfig   *ProxyConfig           `protobuf:"bytes,2,opt,name=proxy_config,json=proxyConfig,proto3,oneof" json:"proxy_config,omitempty"`
	WorkingStatus *ProxyWorkingStatus    `protobuf:"bytes,3,opt,name=working_status,json=workingStatus,proto3,oneof" json:"working_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProxyConfigResponse) Reset() {
	*x = GetProxyConfigResponse{}
	mi := &file_api_client_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProxyConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProxyConfigResponse) ProtoMessage() {}

func (x *GetProxyConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProxyConfigResponse.ProtoReflect.Descriptor instead.
func (*GetProxyConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{27}
}

func (x *GetProxyConfigResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetProxyConfigResponse) GetProxyConfig() *ProxyConfig {
	if x != nil {
		return x.ProxyConfig
	}
	return nil
}

func (x *GetProxyConfigResponse) GetWorkingStatus() *ProxyWorkingStatus {
	if x != nil {
		return x.WorkingStatus
	}
	return nil
}

type StopProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      *string                `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	ServerId      *string                `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3,oneof" json:"server_id,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopProxyRequest) Reset() {
	*x = StopProxyRequest{}
	mi := &file_api_client_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopProxyRequest) ProtoMessage() {}

func (x *StopProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopProxyRequest.ProtoReflect.Descriptor instead.
func (*StopProxyRequest) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{28}
}

func (x *StopProxyRequest) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *StopProxyRequest) GetServerId() string {
	if x != nil && x.ServerId != nil {
		return *x.ServerId
	}
	return ""
}

func (x *StopProxyRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type StopProxyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopProxyResponse) Reset() {
	*x = StopProxyResponse{}
	mi := &file_api_client_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopProxyResponse) ProtoMessage() {}

func (x *StopProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopProxyResponse.ProtoReflect.Descriptor instead.
func (*StopProxyResponse) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{29}
}

func (x *StopProxyResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type StartProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      *string                `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	ServerId      *string                `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3,oneof" json:"server_id,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProxyRequest) Reset() {
	*x = StartProxyRequest{}
	mi := &file_api_client_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProxyRequest) ProtoMessage() {}

func (x *StartProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProxyRequest.ProtoReflect.Descriptor instead.
func (*StartProxyRequest) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{30}
}

func (x *StartProxyRequest) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *StartProxyRequest) GetServerId() string {
	if x != nil && x.ServerId != nil {
		return *x.ServerId
	}
	return ""
}

func (x *StartProxyRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type StartProxyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProxyResponse) Reset() {
	*x = StartProxyResponse{}
	mi := &file_api_client_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProxyResponse) ProtoMessage() {}

func (x *StartProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProxyResponse.ProtoReflect.Descriptor instead.
func (*StartProxyResponse) Descriptor() ([]byte, []int) {
	return file_api_client_proto_rawDescGZIP(), []int{31}
}

func (x *StartProxyResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_api_client_proto protoreflect.FileDescriptor

const file_api_client_proto_rawDesc = "" +
	"\n" +
	"\x10api_client.proto\x12\n" +
	"api_client\x1a\fcommon.proto\"t\n" +
	"\x11InitClientRequest\x12 \n" +
	"\tclient_id\x18\x01 \x01(\tH\x00R\bclientId\x88\x01\x01\x12!\n" +
	"\tephemeral\x18\x02 \x01(\bH\x01R\tephemeral\x88\x01\x01B\f\n" +
	"\n" +
	"_client_idB\f\n" +
	"\n" +
	"_ephemeral\"|\n" +
	"\x12InitClientResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusH\x00R\x06status\x88\x01\x01\x12 \n" +
	"\tclient_id\x18\x02 \x01(\tH\x01R\bclientId\x88\x01\x01B\t\n" +
	"\a_statusB\f\n" +
	"\n" +
	"_client_id\"\x91\x01\n" +
	"\x12ListClientsRequest\x12\x17\n" +
	"\x04page\x18\x01 \x01(\x05H\x00R\x04page\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x02 \x01(\x05H\x01R\bpageSize\x88\x01\x01\x12\x1d\n" +
	"\akeyword\x18\x03 \x01(\tH\x02R\akeyword\x88\x01\x01B\a\n" +
	"\x05_pageB\f\n" +
	"\n" +
	"_page_sizeB\n" +
	"\n" +
	"\b_keyword\"\x9c\x01\n" +
	"\x13ListClientsResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusH\x00R\x06status\x88\x01\x01\x12\x19\n" +
	"\x05total\x18\x02 \x01(\x05H\x01R\x05total\x88\x01\x01\x12(\n" +
	"\aclients\x18\x03 \x03(\v2\x0e.common.ClientR\aclientsB\t\n" +
	"\a_statusB\b\n" +
	"\x06_total\"r\n" +
	"\x10GetClientRequest\x12 \n" +
	"\tclient_id\x18\x01 \x01(\tH\x00R\bclientId\x88\x01\x01\x12 \n" +
	"\tserver_id\x18\x02 \x01(\tH\x01R\bserverId\x88\x01\x01B\f\n" +
	"\n" +
	"_client_idB\f\n" +
	"\n" +
	"_server_id\"\x83\x01\n" +
	"\x11GetClientResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusH\x00R\x06status\x88\x01\x01\x12+\n" +
	"\x06client\x18\x02 \x01(\v2\x0e.common.ClientH\x01R\x06client\x88\x01\x01B\t\n" +
	"\a_statusB\t\n" +
	"\a_client\"E\n" +
	"\x13DeleteClientRequest\x12 \n" +
	"\tclient_id\x18\x01 \x01(\tH\x00R\bclientId\x88\x01\x01B\f\n" +
	"\n" +
	"_client_id\"N\n" +
	"\x14DeleteClientResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"\xf3\x01\n" +
	"\x11UpdateFRPCRequest\x12 \n" +
	"\tclient_id\x18\x01 \x01(\tH\x00R\bclientId\x88\x01\x01\x12 \n" +
	"\tserver_id\x18\x02 \x01(\tH\x01R\bserverId\x88\x01\x01\x12\x1b\n" +
	"\x06config\x18\x03 \x01(\fH\x02R\x06config\x88\x01\x01\x12\x1d\n" +
	"\acomment\x18\x04 \x01(\tH\x03R\acomment\x88\x01\x01\x12\x1e\n" +
	"\bfrps_url\x18\x05 \x01(\tH\x04R\afrpsUrl\x88\x01\x01B\f\n" +
	"\n" +
	"_client_idB\f\n" +
	"\n" +
	"_server_idB\t\n" +
	"\a_configB\n" +
	"\n" +
	"\b_commentB\v\n" +
	"\t_frps_url\"L\n" +
	"\x12UpdateFRPCResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"C\n" +
	"\x11RemoveFRPCRequest\x12 \n" +
	"\tclient_id\x18\x01 \x01(\tH\x00R\bclientId\x88\x01\x01B\f\n" +
	"\n" +
	"_client_id\"L\n" +
	"\x12RemoveFRPCResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"A\n" +
	"\x0fStopFRPCRequest\x12 \n" +
	"\tclient_id\x18\x01 \x01(\tH\x00R\bclientId\x88\x01\x01B\f\n" +
	"\n" +
	"_client_id\"J\n" +
	"\x10StopFRPCResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"B\n" +
	"\x10StartFRPCRequest\x12 \n" +
	"\tclient_id\x18\x01 \x01(\tH\x00R\bclientId\x88\x01\x01B\f\n" +
	"\n" +
	"_client_id\"K\n" +
	"\x11StartFRPCResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"P\n" +
	"\x1eGetProxyStatsByClientIDRequest\x12 \n" +
	"\tclient_id\x18\x01 \x01(\tH\x00R\bclientId\x88\x01\x01B\f\n" +
	"\n" +
	"_client_id\"\x8d\x01\n" +
	"\x1fGetProxyStatsByClientIDResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusH\x00R\x06status\x88\x01\x01\x122\n" +
	"\vproxy_infos\x18\x02 \x03(\v2\x11.common.ProxyInfoR\n" +
	"proxyInfosB\t\n" +
	"\a_status\"\xf6\x01\n" +
	"\x17ListProxyConfigsRequest\x12\x17\n" +
	"\x04page\x18\x01 \x01(\x05H\x00R\x04page\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x02 \x01(\x05H\x01R\bpageSize\x88\x01\x01\x12\x1d\n" +
	"\akeyword\x18\x03 \x01(\tH\x02R\akeyword\x88\x01\x01\x12 \n" +
	"\tclient_id\x18\x04 \x01(\tH\x03R\bclientId\x88\x01\x01\x12 \n" +
	"\tserver_id\x18\x05 \x01(\tH\x04R\bserverId\x88\x01\x01B\a\n" +
	"\x05_pageB\f\n" +
	"\n" +
	"_page_sizeB\n" +
	"\n" +
	"\b_keywordB\f\n" +
	"\n" +
	"_client_idB\f\n" +
	"\n" +
	"_server_id\"\xb1\x01\n" +
	"\x18ListProxyConfigsResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusH\x00R\x06status\x88\x01\x01\x12\x19\n" +
	"\x05total\x18\x02 \x01(\x05H\x01R\x05total\x88\x01\x01\x128\n" +
	"\rproxy_configs\x18\x03 \x03(\v2\x13.common.ProxyConfigR\fproxyConfigsB\t\n" +
	"\a_statusB\b\n" +
	"\x06_total\"\xd3\x01\n" +
	"\x18CreateProxyConfigRequest\x12 \n" +
	"\tclient_id\x18\x01 \x01(\tH\x00R\bclientId\x88\x01\x01\x12 \n" +
	"\tserver_id\x18\x02 \x01(\tH\x01R\bserverId\x88\x01\x01\x12\x1b\n" +
	"\x06config\x18\x03 \x01(\fH\x02R\x06config\x88\x01\x01\x12!\n" +
	"\toverwrite\x18\x04 \x01(\bH\x03R\toverwrite\x88\x01\x01B\f\n" +
	"\n" +
	"_client_idB\f\n" +
	"\n" +
	"_server_idB\t\n" +
	"\a_configB\f\n" +
	"\n" +
	"_overwrite\"S\n" +
	"\x19CreateProxyConfigResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"\x9c\x01\n" +
	"\x18DeleteProxyConfigRequest\x12 \n" +
	"\tclient_id\x18\x01 \x01(\tH\x00R\bclientId\x88\x01\x01\x12 \n" +
	"\tserver_id\x18\x02 \x01(\tH\x01R\bserverId\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x02R\x04name\x88\x01\x01B\f\n" +
	"\n" +
	"_client_idB\f\n" +
	"\n" +
	"_server_idB\a\n" +
	"\x05_name\"S\n" +
	"\x19DeleteProxyConfigResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"\xc4\x01\n" +
	"\x18UpdateProxyConfigRequest\x12 \n" +
	"\tclient_id\x18\x01 \x01(\tH\x00R\bclientId\x88\x01\x01\x12 \n" +
	"\tserver_id\x18\x02 \x01(\tH\x01R\bserverId\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x02R\x04name\x88\x01\x01\x12\x1b\n" +
	"\x06config\x18\x04 \x01(\fH\x03R\x06config\x88\x01\x01B\f\n" +
	"\n" +
	"_client_idB\f\n" +
	"\n" +
	"_server_idB\a\n" +
	"\x05_nameB\t\n" +
	"\a_config\"S\n" +
	"\x19UpdateProxyConfigResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"\x99\x01\n" +
	"\x15GetProxyConfigRequest\x12 \n" +
	"\tclient_id\x18\x01 \x01(\tH\x00R\bclientId\x88\x01\x01\x12 \n" +
	"\tserver_id\x18\x02 \x01(\tH\x01R\bserverId\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x02R\x04name\x88\x01\x01B\f\n" +
	"\n" +
	"_client_idB\f\n" +
	"\n" +
	"_server_idB\a\n" +
	"\x05_name\"\xf9\x01\n" +
	"\x16GetProxyConfigResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusH\x00R\x06status\x88\x01\x01\x12;\n" +
	"\fproxy_config\x18\x02 \x01(\v2\x13.common.ProxyConfigH\x01R\vproxyConfig\x88\x01\x01\x12F\n" +
	"\x0eworking_status\x18\x03 \x01(\v2\x1a.common.ProxyWorkingStatusH\x02R\rworkingStatus\x88\x01\x01B\t\n" +
	"\a_statusB\x0f\n" +
	"\r_proxy_configB\x11\n" +
	"\x0f_working_status\"\x94\x01\n" +
	"\x10StopProxyRequest\x12 \n" +
	"\tclient_id\x18\x01 \x01(\tH\x00R\bclientId\x88\x01\x01\x12 \n" +
	"\tserver_id\x18\x02 \x01(\tH\x01R\bserverId\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x02R\x04name\x88\x01\x01B\f\n" +
	"\n" +
	"_client_idB\f\n" +
	"\n" +
	"_server_idB\a\n" +
	"\x05_name\"K\n" +
	"\x11StopProxyResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"\x95\x01\n" +
	"\x11StartProxyRequest\x12 \n" +
	"\tclient_id\x18\x01 \x01(\tH\x00R\bclientId\x88\x01\x01\x12 \n" +
	"\tserver_id\x18\x02 \x01(\tH\x01R\bserverId\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x02R\x04name\x88\x01\x01B\f\n" +
	"\n" +
	"_client_idB\f\n" +
	"\n" +
	"_server_idB\a\n" +
	"\x05_name\"L\n" +
	"\x12StartProxyResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_statusB\aZ\x05../pbb\x06proto3"

var (
	file_api_client_proto_rawDescOnce sync.Once
	file_api_client_proto_rawDescData []byte
)

func file_api_client_proto_rawDescGZIP() []byte {
	file_api_client_proto_rawDescOnce.Do(func() {
		file_api_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_client_proto_rawDesc), len(file_api_client_proto_rawDesc)))
	})
	return file_api_client_proto_rawDescData
}

var file_api_client_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_api_client_proto_goTypes = []any{
	(*InitClientRequest)(nil),               // 0: api_client.InitClientRequest
	(*InitClientResponse)(nil),              // 1: api_client.InitClientResponse
	(*ListClientsRequest)(nil),              // 2: api_client.ListClientsRequest
	(*ListClientsResponse)(nil),             // 3: api_client.ListClientsResponse
	(*GetClientRequest)(nil),                // 4: api_client.GetClientRequest
	(*GetClientResponse)(nil),               // 5: api_client.GetClientResponse
	(*DeleteClientRequest)(nil),             // 6: api_client.DeleteClientRequest
	(*DeleteClientResponse)(nil),            // 7: api_client.DeleteClientResponse
	(*UpdateFRPCRequest)(nil),               // 8: api_client.UpdateFRPCRequest
	(*UpdateFRPCResponse)(nil),              // 9: api_client.UpdateFRPCResponse
	(*RemoveFRPCRequest)(nil),               // 10: api_client.RemoveFRPCRequest
	(*RemoveFRPCResponse)(nil),              // 11: api_client.RemoveFRPCResponse
	(*StopFRPCRequest)(nil),                 // 12: api_client.StopFRPCRequest
	(*StopFRPCResponse)(nil),                // 13: api_client.StopFRPCResponse
	(*StartFRPCRequest)(nil),                // 14: api_client.StartFRPCRequest
	(*StartFRPCResponse)(nil),               // 15: api_client.StartFRPCResponse
	(*GetProxyStatsByClientIDRequest)(nil),  // 16: api_client.GetProxyStatsByClientIDRequest
	(*GetProxyStatsByClientIDResponse)(nil), // 17: api_client.GetProxyStatsByClientIDResponse
	(*ListProxyConfigsRequest)(nil),         // 18: api_client.ListProxyConfigsRequest
	(*ListProxyConfigsResponse)(nil),        // 19: api_client.ListProxyConfigsResponse
	(*CreateProxyConfigRequest)(nil),        // 20: api_client.CreateProxyConfigRequest
	(*CreateProxyConfigResponse)(nil),       // 21: api_client.CreateProxyConfigResponse
	(*DeleteProxyConfigRequest)(nil),        // 22: api_client.DeleteProxyConfigRequest
	(*DeleteProxyConfigResponse)(nil),       // 23: api_client.DeleteProxyConfigResponse
	(*UpdateProxyConfigRequest)(nil),        // 24: api_client.UpdateProxyConfigRequest
	(*UpdateProxyConfigResponse)(nil),       // 25: api_client.UpdateProxyConfigResponse
	(*GetProxyConfigRequest)(nil),           // 26: api_client.GetProxyConfigRequest
	(*GetProxyConfigResponse)(nil),          // 27: api_client.GetProxyConfigResponse
	(*StopProxyRequest)(nil),                // 28: api_client.StopProxyRequest
	(*StopProxyResponse)(nil),               // 29: api_client.StopProxyResponse
	(*StartProxyRequest)(nil),               // 30: api_client.StartProxyRequest
	(*StartProxyResponse)(nil),              // 31: api_client.StartProxyResponse
	(*Status)(nil),                          // 32: common.Status
	(*Client)(nil),                          // 33: common.Client
	(*ProxyInfo)(nil),                       // 34: common.ProxyInfo
	(*ProxyConfig)(nil),                     // 35: common.ProxyConfig
	(*ProxyWorkingStatus)(nil),              // 36: common.ProxyWorkingStatus
}
var file_api_client_proto_depIdxs = []int32{
	32, // 0: api_client.InitClientResponse.status:type_name -> common.Status
	32, // 1: api_client.ListClientsResponse.status:type_name -> common.Status
	33, // 2: api_client.ListClientsResponse.clients:type_name -> common.Client
	32, // 3: api_client.GetClientResponse.status:type_name -> common.Status
	33, // 4: api_client.GetClientResponse.client:type_name -> common.Client
	32, // 5: api_client.DeleteClientResponse.status:type_name -> common.Status
	32, // 6: api_client.UpdateFRPCResponse.status:type_name -> common.Status
	32, // 7: api_client.RemoveFRPCResponse.status:type_name -> common.Status
	32, // 8: api_client.StopFRPCResponse.status:type_name -> common.Status
	32, // 9: api_client.StartFRPCResponse.status:type_name -> common.Status
	32, // 10: api_client.GetProxyStatsByClientIDResponse.status:type_name -> common.Status
	34, // 11: api_client.GetProxyStatsByClientIDResponse.proxy_infos:type_name -> common.ProxyInfo
	32, // 12: api_client.ListProxyConfigsResponse.status:type_name -> common.Status
	35, // 13: api_client.ListProxyConfigsResponse.proxy_configs:type_name -> common.ProxyConfig
	32, // 14: api_client.CreateProxyConfigResponse.status:type_name -> common.Status
	32, // 15: api_client.DeleteProxyConfigResponse.status:type_name -> common.Status
	32, // 16: api_client.UpdateProxyConfigResponse.status:type_name -> common.Status
	32, // 17: api_client.GetProxyConfigResponse.status:type_name -> common.Status
	35, // 18: api_client.GetProxyConfigResponse.proxy_config:type_name -> common.ProxyConfig
	36, // 19: api_client.GetProxyConfigResponse.working_status:type_name -> common.ProxyWorkingStatus
	32, // 20: api_client.StopProxyResponse.status:type_name -> common.Status
	32, // 21: api_client.StartProxyResponse.status:type_name -> common.Status
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_api_client_proto_init() }
func file_api_client_proto_init() {
	if File_api_client_proto != nil {
		return
	}
	file_common_proto_init()
	file_api_client_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_client_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_client_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_client_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_client_proto_msgTypes[4].OneofWrappers = []any{}
	file_api_client_proto_msgTypes[5].OneofWrappers = []any{}
	file_api_client_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_client_proto_msgTypes[7].OneofWrappers = []any{}
	file_api_client_proto_msgTypes[8].OneofWrappers = []any{}
	file_api_client_proto_msgTypes[9].OneofWrappers = []any{}
	file_api_client_proto_msgTypes[10].OneofWrappers = []any{}
	file_api_client_proto_msgTypes[11].OneofWrappers = []any{}
	file_api_client_proto_msgTypes[12].OneofWrappers = []any{}
	file_api_client_proto_msgTypes[13].OneofWrappers = []any{}
	file_api_client_proto_msgTypes[14].OneofWrappers = []any{}
	file_api_client_proto_msgTypes[15].OneofWrappers = []any{}
	file_api_client_proto_msgTypes[16].OneofWrappers = []any{}
	file_api_client_proto_msgTypes[17].OneofWrappers = []any{}
	file_api_client_proto_msgTypes[18].OneofWrappers = []any{}
	file_api_client_proto_msgTypes[19].OneofWrappers = []any{}
	file_api_client_proto_msgTypes[20].OneofWrappers = []any{}
	file_api_client_proto_msgTypes[21].OneofWrappers = []any{}
	file_api_client_proto_msgTypes[22].OneofWrappers = []any{}
	file_api_client_proto_msgTypes[23].OneofWrappers = []any{}
	file_api_client_proto_msgTypes[24].OneofWrappers = []any{}
	file_api_client_proto_msgTypes[25].OneofWrappers = []any{}
	file_api_client_proto_msgTypes[26].OneofWrappers = []any{}
	file_api_client_proto_msgTypes[27].OneofWrappers = []any{}
	file_api_client_proto_msgTypes[28].OneofWrappers = []any{}
	file_api_client_proto_msgTypes[29].OneofWrappers = []any{}
	file_api_client_proto_msgTypes[30].OneofWrappers = []any{}
	file_api_client_proto_msgTypes[31].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_client_proto_rawDesc), len(file_api_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_client_proto_goTypes,
		DependencyIndexes: file_api_client_proto_depIdxs,
		MessageInfos:      file_api_client_proto_msgTypes,
	}.Build()
	File_api_client_proto = out.File
	file_api_client_proto_goTypes = nil
	file_api_client_proto_depIdxs = nil
}
