// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api_master.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientStatus_Status int32

const (
	ClientStatus_STATUS_UNSPECIFIED ClientStatus_Status = 0
	ClientStatus_STATUS_ONLINE      ClientStatus_Status = 1
	ClientStatus_STATUS_OFFLINE     ClientStatus_Status = 2
	ClientStatus_STATUS_ERROR       ClientStatus_Status = 3
)

// Enum value maps for ClientStatus_Status.
var (
	ClientStatus_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_ONLINE",
		2: "STATUS_OFFLINE",
		3: "STATUS_ERROR",
	}
	ClientStatus_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_ONLINE":      1,
		"STATUS_OFFLINE":     2,
		"STATUS_ERROR":       3,
	}
)

func (x ClientStatus_Status) Enum() *ClientStatus_Status {
	p := new(ClientStatus_Status)
	*p = x
	return p
}

func (x ClientStatus_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientStatus_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_master_proto_enumTypes[0].Descriptor()
}

func (ClientStatus_Status) Type() protoreflect.EnumType {
	return &file_api_master_proto_enumTypes[0]
}

func (x ClientStatus_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientStatus_Status.Descriptor instead.
func (ClientStatus_Status) EnumDescriptor() ([]byte, []int) {
	return file_api_master_proto_rawDescGZIP(), []int{0, 0}
}

type ClientStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientType    ClientType             `protobuf:"varint,1,opt,name=client_type,json=clientType,proto3,enum=common.ClientType" json:"client_type,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Status        ClientStatus_Status    `protobuf:"varint,3,opt,name=status,proto3,enum=api_master.ClientStatus_Status" json:"status,omitempty"`
	Ping          int32                  `protobuf:"varint,4,opt,name=ping,proto3" json:"ping,omitempty"` // 单位为毫秒
	Version       *ClientVersion         `protobuf:"bytes,5,opt,name=version,proto3,oneof" json:"version,omitempty"`
	Addr          *string                `protobuf:"bytes,6,opt,name=addr,proto3,oneof" json:"addr,omitempty"`
	ConnectTime   *int64                 `protobuf:"varint,7,opt,name=connect_time,json=connectTime,proto3,oneof" json:"connect_time,omitempty"` // 连接建立的时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientStatus) Reset() {
	*x = ClientStatus{}
	mi := &file_api_master_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStatus) ProtoMessage() {}

func (x *ClientStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_master_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStatus.ProtoReflect.Descriptor instead.
func (*ClientStatus) Descriptor() ([]byte, []int) {
	return file_api_master_proto_rawDescGZIP(), []int{0}
}

func (x *ClientStatus) GetClientType() ClientType {
	if x != nil {
		return x.ClientType
	}
	return ClientType_CLIENT_TYPE_UNSPECIFIED
}

func (x *ClientStatus) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientStatus) GetStatus() ClientStatus_Status {
	if x != nil {
		return x.Status
	}
	return ClientStatus_STATUS_UNSPECIFIED
}

func (x *ClientStatus) GetPing() int32 {
	if x != nil {
		return x.Ping
	}
	return 0
}

func (x *ClientStatus) GetVersion() *ClientVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *ClientStatus) GetAddr() string {
	if x != nil && x.Addr != nil {
		return *x.Addr
	}
	return ""
}

func (x *ClientStatus) GetConnectTime() int64 {
	if x != nil && x.ConnectTime != nil {
		return *x.ConnectTime
	}
	return 0
}

type ClientVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GitVersion    string                 `protobuf:"bytes,1,opt,name=GitVersion,proto3" json:"GitVersion,omitempty"`
	GitCommit     string                 `protobuf:"bytes,2,opt,name=GitCommit,proto3" json:"GitCommit,omitempty"`
	BuildDate     string                 `protobuf:"bytes,3,opt,name=BuildDate,proto3" json:"BuildDate,omitempty"`
	GoVersion     string                 `protobuf:"bytes,4,opt,name=GoVersion,proto3" json:"GoVersion,omitempty"`
	Compiler      string                 `protobuf:"bytes,5,opt,name=Compiler,proto3" json:"Compiler,omitempty"`
	Platform      string                 `protobuf:"bytes,6,opt,name=Platform,proto3" json:"Platform,omitempty"`
	GitBranch     string                 `protobuf:"bytes,7,opt,name=GitBranch,proto3" json:"GitBranch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientVersion) Reset() {
	*x = ClientVersion{}
	mi := &file_api_master_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientVersion) ProtoMessage() {}

func (x *ClientVersion) ProtoReflect() protoreflect.Message {
	mi := &file_api_master_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientVersion.ProtoReflect.Descriptor instead.
func (*ClientVersion) Descriptor() ([]byte, []int) {
	return file_api_master_proto_rawDescGZIP(), []int{1}
}

func (x *ClientVersion) GetGitVersion() string {
	if x != nil {
		return x.GitVersion
	}
	return ""
}

func (x *ClientVersion) GetGitCommit() string {
	if x != nil {
		return x.GitCommit
	}
	return ""
}

func (x *ClientVersion) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

func (x *ClientVersion) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

func (x *ClientVersion) GetCompiler() string {
	if x != nil {
		return x.Compiler
	}
	return ""
}

func (x *ClientVersion) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ClientVersion) GetGitBranch() string {
	if x != nil {
		return x.GitBranch
	}
	return ""
}

type GetClientsStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientType    ClientType             `protobuf:"varint,1,opt,name=client_type,json=clientType,proto3,enum=common.ClientType" json:"client_type,omitempty"`
	ClientIds     []string               `protobuf:"bytes,2,rep,name=client_ids,json=clientIds,proto3" json:"client_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientsStatusRequest) Reset() {
	*x = GetClientsStatusRequest{}
	mi := &file_api_master_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientsStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientsStatusRequest) ProtoMessage() {}

func (x *GetClientsStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_master_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientsStatusRequest.ProtoReflect.Descriptor instead.
func (*GetClientsStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_master_proto_rawDescGZIP(), []int{2}
}

func (x *GetClientsStatusRequest) GetClientType() ClientType {
	if x != nil {
		return x.ClientType
	}
	return ClientType_CLIENT_TYPE_UNSPECIFIED
}

func (x *GetClientsStatusRequest) GetClientIds() []string {
	if x != nil {
		return x.ClientIds
	}
	return nil
}

type GetClientsStatusResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Status        *Status                  `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Clients       map[string]*ClientStatus `protobuf:"bytes,2,rep,name=clients,proto3" json:"clients,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientsStatusResponse) Reset() {
	*x = GetClientsStatusResponse{}
	mi := &file_api_master_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientsStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientsStatusResponse) ProtoMessage() {}

func (x *GetClientsStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_master_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientsStatusResponse.ProtoReflect.Descriptor instead.
func (*GetClientsStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_master_proto_rawDescGZIP(), []int{3}
}

func (x *GetClientsStatusResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetClientsStatusResponse) GetClients() map[string]*ClientStatus {
	if x != nil {
		return x.Clients
	}
	return nil
}

type GetClientCertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientType    ClientType             `protobuf:"varint,1,opt,name=client_type,json=clientType,proto3,enum=common.ClientType" json:"client_type,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientCertRequest) Reset() {
	*x = GetClientCertRequest{}
	mi := &file_api_master_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientCertRequest) ProtoMessage() {}

func (x *GetClientCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_master_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientCertRequest.ProtoReflect.Descriptor instead.
func (*GetClientCertRequest) Descriptor() ([]byte, []int) {
	return file_api_master_proto_rawDescGZIP(), []int{4}
}

func (x *GetClientCertRequest) GetClientType() ClientType {
	if x != nil {
		return x.ClientType
	}
	return ClientType_CLIENT_TYPE_UNSPECIFIED
}

func (x *GetClientCertRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GetClientCertRequest) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

type GetClientCertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Cert          []byte                 `protobuf:"bytes,2,opt,name=cert,proto3" json:"cert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientCertResponse) Reset() {
	*x = GetClientCertResponse{}
	mi := &file_api_master_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientCertResponse) ProtoMessage() {}

func (x *GetClientCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_master_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientCertResponse.ProtoReflect.Descriptor instead.
func (*GetClientCertResponse) Descriptor() ([]byte, []int) {
	return file_api_master_proto_rawDescGZIP(), []int{5}
}

func (x *GetClientCertResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetClientCertResponse) GetCert() []byte {
	if x != nil {
		return x.Cert
	}
	return nil
}

var File_api_master_proto protoreflect.FileDescriptor

const file_api_master_proto_rawDesc = "" +
	"\n" +
	"\x10api_master.proto\x12\n" +
	"api_master\x1a\fcommon.proto\"\xa9\x03\n" +
	"\fClientStatus\x123\n" +
	"\vclient_type\x18\x01 \x01(\x0e2\x12.common.ClientTypeR\n" +
	"clientType\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x127\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1f.api_master.ClientStatus.StatusR\x06status\x12\x12\n" +
	"\x04ping\x18\x04 \x01(\x05R\x04ping\x128\n" +
	"\aversion\x18\x05 \x01(\v2\x19.api_master.ClientVersionH\x00R\aversion\x88\x01\x01\x12\x17\n" +
	"\x04addr\x18\x06 \x01(\tH\x01R\x04addr\x88\x01\x01\x12&\n" +
	"\fconnect_time\x18\a \x01(\x03H\x02R\vconnectTime\x88\x01\x01\"Y\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_ONLINE\x10\x01\x12\x12\n" +
	"\x0eSTATUS_OFFLINE\x10\x02\x12\x10\n" +
	"\fSTATUS_ERROR\x10\x03B\n" +
	"\n" +
	"\b_versionB\a\n" +
	"\x05_addrB\x0f\n" +
	"\r_connect_time\"\xdf\x01\n" +
	"\rClientVersion\x12\x1e\n" +
	"\n" +
	"GitVersion\x18\x01 \x01(\tR\n" +
	"GitVersion\x12\x1c\n" +
	"\tGitCommit\x18\x02 \x01(\tR\tGitCommit\x12\x1c\n" +
	"\tBuildDate\x18\x03 \x01(\tR\tBuildDate\x12\x1c\n" +
	"\tGoVersion\x18\x04 \x01(\tR\tGoVersion\x12\x1a\n" +
	"\bCompiler\x18\x05 \x01(\tR\bCompiler\x12\x1a\n" +
	"\bPlatform\x18\x06 \x01(\tR\bPlatform\x12\x1c\n" +
	"\tGitBranch\x18\a \x01(\tR\tGitBranch\"m\n" +
	"\x17GetClientsStatusRequest\x123\n" +
	"\vclient_type\x18\x01 \x01(\x0e2\x12.common.ClientTypeR\n" +
	"clientType\x12\x1d\n" +
	"\n" +
	"client_ids\x18\x02 \x03(\tR\tclientIds\"\xf5\x01\n" +
	"\x18GetClientsStatusResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusH\x00R\x06status\x88\x01\x01\x12K\n" +
	"\aclients\x18\x02 \x03(\v21.api_master.GetClientsStatusResponse.ClientsEntryR\aclients\x1aT\n" +
	"\fClientsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.api_master.ClientStatusR\x05value:\x028\x01B\t\n" +
	"\a_status\"\x8d\x01\n" +
	"\x14GetClientCertRequest\x123\n" +
	"\vclient_type\x18\x01 \x01(\x0e2\x12.common.ClientTypeR\n" +
	"clientType\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x03 \x01(\tR\fclientSecret\"c\n" +
	"\x15GetClientCertResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusH\x00R\x06status\x88\x01\x01\x12\x12\n" +
	"\x04cert\x18\x02 \x01(\fR\x04certB\t\n" +
	"\a_statusB\aZ\x05../pbb\x06proto3"

var (
	file_api_master_proto_rawDescOnce sync.Once
	file_api_master_proto_rawDescData []byte
)

func file_api_master_proto_rawDescGZIP() []byte {
	file_api_master_proto_rawDescOnce.Do(func() {
		file_api_master_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_master_proto_rawDesc), len(file_api_master_proto_rawDesc)))
	})
	return file_api_master_proto_rawDescData
}

var file_api_master_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_master_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_master_proto_goTypes = []any{
	(ClientStatus_Status)(0),         // 0: api_master.ClientStatus.Status
	(*ClientStatus)(nil),             // 1: api_master.ClientStatus
	(*ClientVersion)(nil),            // 2: api_master.ClientVersion
	(*GetClientsStatusRequest)(nil),  // 3: api_master.GetClientsStatusRequest
	(*GetClientsStatusResponse)(nil), // 4: api_master.GetClientsStatusResponse
	(*GetClientCertRequest)(nil),     // 5: api_master.GetClientCertRequest
	(*GetClientCertResponse)(nil),    // 6: api_master.GetClientCertResponse
	nil,                              // 7: api_master.GetClientsStatusResponse.ClientsEntry
	(ClientType)(0),                  // 8: common.ClientType
	(*Status)(nil),                   // 9: common.Status
}
var file_api_master_proto_depIdxs = []int32{
	8, // 0: api_master.ClientStatus.client_type:type_name -> common.ClientType
	0, // 1: api_master.ClientStatus.status:type_name -> api_master.ClientStatus.Status
	2, // 2: api_master.ClientStatus.version:type_name -> api_master.ClientVersion
	8, // 3: api_master.GetClientsStatusRequest.client_type:type_name -> common.ClientType
	9, // 4: api_master.GetClientsStatusResponse.status:type_name -> common.Status
	7, // 5: api_master.GetClientsStatusResponse.clients:type_name -> api_master.GetClientsStatusResponse.ClientsEntry
	8, // 6: api_master.GetClientCertRequest.client_type:type_name -> common.ClientType
	9, // 7: api_master.GetClientCertResponse.status:type_name -> common.Status
	1, // 8: api_master.GetClientsStatusResponse.ClientsEntry.value:type_name -> api_master.ClientStatus
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_api_master_proto_init() }
func file_api_master_proto_init() {
	if File_api_master_proto != nil {
		return
	}
	file_common_proto_init()
	file_api_master_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_master_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_master_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_master_proto_rawDesc), len(file_api_master_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_master_proto_goTypes,
		DependencyIndexes: file_api_master_proto_depIdxs,
		EnumInfos:         file_api_master_proto_enumTypes,
		MessageInfos:      file_api_master_proto_msgTypes,
	}.Build()
	File_api_master_proto = out.File
	file_api_master_proto_goTypes = nil
	file_api_master_proto_depIdxs = nil
}
