// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api_server.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      *string                `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3,oneof" json:"server_id,omitempty"`
	ServerIp      *string                `protobuf:"bytes,2,opt,name=server_ip,json=serverIp,proto3,oneof" json:"server_ip,omitempty"`
	Comment       *string                `protobuf:"bytes,3,opt,name=comment,proto3,oneof" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitServerRequest) Reset() {
	*x = InitServerRequest{}
	mi := &file_api_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitServerRequest) ProtoMessage() {}

func (x *InitServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitServerRequest.ProtoReflect.Descriptor instead.
func (*InitServerRequest) Descriptor() ([]byte, []int) {
	return file_api_server_proto_rawDescGZIP(), []int{0}
}

func (x *InitServerRequest) GetServerId() string {
	if x != nil && x.ServerId != nil {
		return *x.ServerId
	}
	return ""
}

func (x *InitServerRequest) GetServerIp() string {
	if x != nil && x.ServerIp != nil {
		return *x.ServerIp
	}
	return ""
}

func (x *InitServerRequest) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

type InitServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	ServerId      *string                `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3,oneof" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitServerResponse) Reset() {
	*x = InitServerResponse{}
	mi := &file_api_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitServerResponse) ProtoMessage() {}

func (x *InitServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitServerResponse.ProtoReflect.Descriptor instead.
func (*InitServerResponse) Descriptor() ([]byte, []int) {
	return file_api_server_proto_rawDescGZIP(), []int{1}
}

func (x *InitServerResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *InitServerResponse) GetServerId() string {
	if x != nil && x.ServerId != nil {
		return *x.ServerId
	}
	return ""
}

type ListServersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *int32                 `protobuf:"varint,1,opt,name=page,proto3,oneof" json:"page,omitempty"`
	PageSize      *int32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	Keyword       *string                `protobuf:"bytes,3,opt,name=keyword,proto3,oneof" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServersRequest) Reset() {
	*x = ListServersRequest{}
	mi := &file_api_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServersRequest) ProtoMessage() {}

func (x *ListServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServersRequest.ProtoReflect.Descriptor instead.
func (*ListServersRequest) Descriptor() ([]byte, []int) {
	return file_api_server_proto_rawDescGZIP(), []int{2}
}

func (x *ListServersRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListServersRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListServersRequest) GetKeyword() string {
	if x != nil && x.Keyword != nil {
		return *x.Keyword
	}
	return ""
}

type ListServersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Total         *int32                 `protobuf:"varint,2,opt,name=total,proto3,oneof" json:"total,omitempty"`
	Servers       []*Server              `protobuf:"bytes,3,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServersResponse) Reset() {
	*x = ListServersResponse{}
	mi := &file_api_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServersResponse) ProtoMessage() {}

func (x *ListServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServersResponse.ProtoReflect.Descriptor instead.
func (*ListServersResponse) Descriptor() ([]byte, []int) {
	return file_api_server_proto_rawDescGZIP(), []int{3}
}

func (x *ListServersResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListServersResponse) GetTotal() int32 {
	if x != nil && x.Total != nil {
		return *x.Total
	}
	return 0
}

func (x *ListServersResponse) GetServers() []*Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

type GetServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      *string                `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3,oneof" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerRequest) Reset() {
	*x = GetServerRequest{}
	mi := &file_api_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerRequest) ProtoMessage() {}

func (x *GetServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerRequest.ProtoReflect.Descriptor instead.
func (*GetServerRequest) Descriptor() ([]byte, []int) {
	return file_api_server_proto_rawDescGZIP(), []int{4}
}

func (x *GetServerRequest) GetServerId() string {
	if x != nil && x.ServerId != nil {
		return *x.ServerId
	}
	return ""
}

type GetServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Server        *Server                `protobuf:"bytes,2,opt,name=server,proto3,oneof" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerResponse) Reset() {
	*x = GetServerResponse{}
	mi := &file_api_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerResponse) ProtoMessage() {}

func (x *GetServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerResponse.ProtoReflect.Descriptor instead.
func (*GetServerResponse) Descriptor() ([]byte, []int) {
	return file_api_server_proto_rawDescGZIP(), []int{5}
}

func (x *GetServerResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetServerResponse) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

type DeleteServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      *string                `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3,oneof" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServerRequest) Reset() {
	*x = DeleteServerRequest{}
	mi := &file_api_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerRequest) ProtoMessage() {}

func (x *DeleteServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServerRequest.ProtoReflect.Descriptor instead.
func (*DeleteServerRequest) Descriptor() ([]byte, []int) {
	return file_api_server_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteServerRequest) GetServerId() string {
	if x != nil && x.ServerId != nil {
		return *x.ServerId
	}
	return ""
}

type DeleteServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServerResponse) Reset() {
	*x = DeleteServerResponse{}
	mi := &file_api_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerResponse) ProtoMessage() {}

func (x *DeleteServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServerResponse.ProtoReflect.Descriptor instead.
func (*DeleteServerResponse) Descriptor() ([]byte, []int) {
	return file_api_server_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteServerResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type UpdateFRPSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      *string                `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3,oneof" json:"server_id,omitempty"`
	Config        []byte                 `protobuf:"bytes,2,opt,name=config,proto3,oneof" json:"config,omitempty"`
	Comment       *string                `protobuf:"bytes,3,opt,name=comment,proto3,oneof" json:"comment,omitempty"`
	ServerIp      *string                `protobuf:"bytes,4,opt,name=server_ip,json=serverIp,proto3,oneof" json:"server_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFRPSRequest) Reset() {
	*x = UpdateFRPSRequest{}
	mi := &file_api_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFRPSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFRPSRequest) ProtoMessage() {}

func (x *UpdateFRPSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFRPSRequest.ProtoReflect.Descriptor instead.
func (*UpdateFRPSRequest) Descriptor() ([]byte, []int) {
	return file_api_server_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateFRPSRequest) GetServerId() string {
	if x != nil && x.ServerId != nil {
		return *x.ServerId
	}
	return ""
}

func (x *UpdateFRPSRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *UpdateFRPSRequest) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

func (x *UpdateFRPSRequest) GetServerIp() string {
	if x != nil && x.ServerIp != nil {
		return *x.ServerIp
	}
	return ""
}

type UpdateFRPSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFRPSResponse) Reset() {
	*x = UpdateFRPSResponse{}
	mi := &file_api_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFRPSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFRPSResponse) ProtoMessage() {}

func (x *UpdateFRPSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFRPSResponse.ProtoReflect.Descriptor instead.
func (*UpdateFRPSResponse) Descriptor() ([]byte, []int) {
	return file_api_server_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateFRPSResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type RemoveFRPSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      *string                `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3,oneof" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFRPSRequest) Reset() {
	*x = RemoveFRPSRequest{}
	mi := &file_api_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFRPSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFRPSRequest) ProtoMessage() {}

func (x *RemoveFRPSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFRPSRequest.ProtoReflect.Descriptor instead.
func (*RemoveFRPSRequest) Descriptor() ([]byte, []int) {
	return file_api_server_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveFRPSRequest) GetServerId() string {
	if x != nil && x.ServerId != nil {
		return *x.ServerId
	}
	return ""
}

type RemoveFRPSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFRPSResponse) Reset() {
	*x = RemoveFRPSResponse{}
	mi := &file_api_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFRPSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFRPSResponse) ProtoMessage() {}

func (x *RemoveFRPSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFRPSResponse.ProtoReflect.Descriptor instead.
func (*RemoveFRPSResponse) Descriptor() ([]byte, []int) {
	return file_api_server_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveFRPSResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type StopFRPSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      *string                `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3,oneof" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopFRPSRequest) Reset() {
	*x = StopFRPSRequest{}
	mi := &file_api_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopFRPSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopFRPSRequest) ProtoMessage() {}

func (x *StopFRPSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopFRPSRequest.ProtoReflect.Descriptor instead.
func (*StopFRPSRequest) Descriptor() ([]byte, []int) {
	return file_api_server_proto_rawDescGZIP(), []int{12}
}

func (x *StopFRPSRequest) GetServerId() string {
	if x != nil && x.ServerId != nil {
		return *x.ServerId
	}
	return ""
}

type StopFRPSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopFRPSResponse) Reset() {
	*x = StopFRPSResponse{}
	mi := &file_api_server_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopFRPSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopFRPSResponse) ProtoMessage() {}

func (x *StopFRPSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopFRPSResponse.ProtoReflect.Descriptor instead.
func (*StopFRPSResponse) Descriptor() ([]byte, []int) {
	return file_api_server_proto_rawDescGZIP(), []int{13}
}

func (x *StopFRPSResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type StartFRPSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      *string                `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3,oneof" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartFRPSRequest) Reset() {
	*x = StartFRPSRequest{}
	mi := &file_api_server_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartFRPSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartFRPSRequest) ProtoMessage() {}

func (x *StartFRPSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartFRPSRequest.ProtoReflect.Descriptor instead.
func (*StartFRPSRequest) Descriptor() ([]byte, []int) {
	return file_api_server_proto_rawDescGZIP(), []int{14}
}

func (x *StartFRPSRequest) GetServerId() string {
	if x != nil && x.ServerId != nil {
		return *x.ServerId
	}
	return ""
}

type StartFRPSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartFRPSResponse) Reset() {
	*x = StartFRPSResponse{}
	mi := &file_api_server_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartFRPSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartFRPSResponse) ProtoMessage() {}

func (x *StartFRPSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartFRPSResponse.ProtoReflect.Descriptor instead.
func (*StartFRPSResponse) Descriptor() ([]byte, []int) {
	return file_api_server_proto_rawDescGZIP(), []int{15}
}

func (x *StartFRPSResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetProxyStatsByServerIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      *string                `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3,oneof" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProxyStatsByServerIDRequest) Reset() {
	*x = GetProxyStatsByServerIDRequest{}
	mi := &file_api_server_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProxyStatsByServerIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProxyStatsByServerIDRequest) ProtoMessage() {}

func (x *GetProxyStatsByServerIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProxyStatsByServerIDRequest.ProtoReflect.Descriptor instead.
func (*GetProxyStatsByServerIDRequest) Descriptor() ([]byte, []int) {
	return file_api_server_proto_rawDescGZIP(), []int{16}
}

func (x *GetProxyStatsByServerIDRequest) GetServerId() string {
	if x != nil && x.ServerId != nil {
		return *x.ServerId
	}
	return ""
}

type GetProxyStatsByServerIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	ProxyInfos    []*ProxyInfo           `protobuf:"bytes,2,rep,name=proxy_infos,json=proxyInfos,proto3" json:"proxy_infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProxyStatsByServerIDResponse) Reset() {
	*x = GetProxyStatsByServerIDResponse{}
	mi := &file_api_server_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProxyStatsByServerIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProxyStatsByServerIDResponse) ProtoMessage() {}

func (x *GetProxyStatsByServerIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProxyStatsByServerIDResponse.ProtoReflect.Descriptor instead.
func (*GetProxyStatsByServerIDResponse) Descriptor() ([]byte, []int) {
	return file_api_server_proto_rawDescGZIP(), []int{17}
}

func (x *GetProxyStatsByServerIDResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetProxyStatsByServerIDResponse) GetProxyInfos() []*ProxyInfo {
	if x != nil {
		return x.ProxyInfos
	}
	return nil
}

var File_api_server_proto protoreflect.FileDescriptor

const file_api_server_proto_rawDesc = "" +
	"\n" +
	"\x10api_server.proto\x12\n" +
	"api_server\x1a\fcommon.proto\"\x9e\x01\n" +
	"\x11InitServerRequest\x12 \n" +
	"\tserver_id\x18\x01 \x01(\tH\x00R\bserverId\x88\x01\x01\x12 \n" +
	"\tserver_ip\x18\x02 \x01(\tH\x01R\bserverIp\x88\x01\x01\x12\x1d\n" +
	"\acomment\x18\x03 \x01(\tH\x02R\acomment\x88\x01\x01B\f\n" +
	"\n" +
	"_server_idB\f\n" +
	"\n" +
	"_server_ipB\n" +
	"\n" +
	"\b_comment\"|\n" +
	"\x12InitServerResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusH\x00R\x06status\x88\x01\x01\x12 \n" +
	"\tserver_id\x18\x02 \x01(\tH\x01R\bserverId\x88\x01\x01B\t\n" +
	"\a_statusB\f\n" +
	"\n" +
	"_server_id\"\x91\x01\n" +
	"\x12ListServersRequest\x12\x17\n" +
	"\x04page\x18\x01 \x01(\x05H\x00R\x04page\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x02 \x01(\x05H\x01R\bpageSize\x88\x01\x01\x12\x1d\n" +
	"\akeyword\x18\x03 \x01(\tH\x02R\akeyword\x88\x01\x01B\a\n" +
	"\x05_pageB\f\n" +
	"\n" +
	"_page_sizeB\n" +
	"\n" +
	"\b_keyword\"\x9c\x01\n" +
	"\x13ListServersResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusH\x00R\x06status\x88\x01\x01\x12\x19\n" +
	"\x05total\x18\x02 \x01(\x05H\x01R\x05total\x88\x01\x01\x12(\n" +
	"\aservers\x18\x03 \x03(\v2\x0e.common.ServerR\aserversB\t\n" +
	"\a_statusB\b\n" +
	"\x06_total\"B\n" +
	"\x10GetServerRequest\x12 \n" +
	"\tserver_id\x18\x01 \x01(\tH\x00R\bserverId\x88\x01\x01B\f\n" +
	"\n" +
	"_server_id\"\x83\x01\n" +
	"\x11GetServerResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusH\x00R\x06status\x88\x01\x01\x12+\n" +
	"\x06server\x18\x02 \x01(\v2\x0e.common.ServerH\x01R\x06server\x88\x01\x01B\t\n" +
	"\a_statusB\t\n" +
	"\a_server\"E\n" +
	"\x13DeleteServerRequest\x12 \n" +
	"\tserver_id\x18\x01 \x01(\tH\x00R\bserverId\x88\x01\x01B\f\n" +
	"\n" +
	"_server_id\"N\n" +
	"\x14DeleteServerResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"\xc6\x01\n" +
	"\x11UpdateFRPSRequest\x12 \n" +
	"\tserver_id\x18\x01 \x01(\tH\x00R\bserverId\x88\x01\x01\x12\x1b\n" +
	"\x06config\x18\x02 \x01(\fH\x01R\x06config\x88\x01\x01\x12\x1d\n" +
	"\acomment\x18\x03 \x01(\tH\x02R\acomment\x88\x01\x01\x12 \n" +
	"\tserver_ip\x18\x04 \x01(\tH\x03R\bserverIp\x88\x01\x01B\f\n" +
	"\n" +
	"_server_idB\t\n" +
	"\a_configB\n" +
	"\n" +
	"\b_commentB\f\n" +
	"\n" +
	"_server_ip\"L\n" +
	"\x12UpdateFRPSResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"C\n" +
	"\x11RemoveFRPSRequest\x12 \n" +
	"\tserver_id\x18\x01 \x01(\tH\x00R\bserverId\x88\x01\x01B\f\n" +
	"\n" +
	"_server_id\"L\n" +
	"\x12RemoveFRPSResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"A\n" +
	"\x0fStopFRPSRequest\x12 \n" +
	"\tserver_id\x18\x01 \x01(\tH\x00R\bserverId\x88\x01\x01B\f\n" +
	"\n" +
	"_server_id\"J\n" +
	"\x10StopFRPSResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"B\n" +
	"\x10StartFRPSRequest\x12 \n" +
	"\tserver_id\x18\x01 \x01(\tH\x00R\bserverId\x88\x01\x01B\f\n" +
	"\n" +
	"_server_id\"K\n" +
	"\x11StartFRPSResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"P\n" +
	"\x1eGetProxyStatsByServerIDRequest\x12 \n" +
	"\tserver_id\x18\x01 \x01(\tH\x00R\bserverId\x88\x01\x01B\f\n" +
	"\n" +
	"_server_id\"\x8d\x01\n" +
	"\x1fGetProxyStatsByServerIDResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusH\x00R\x06status\x88\x01\x01\x122\n" +
	"\vproxy_infos\x18\x02 \x03(\v2\x11.common.ProxyInfoR\n" +
	"proxyInfosB\t\n" +
	"\a_statusB\aZ\x05../pbb\x06proto3"

var (
	file_api_server_proto_rawDescOnce sync.Once
	file_api_server_proto_rawDescData []byte
)

func file_api_server_proto_rawDescGZIP() []byte {
	file_api_server_proto_rawDescOnce.Do(func() {
		file_api_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_server_proto_rawDesc), len(file_api_server_proto_rawDesc)))
	})
	return file_api_server_proto_rawDescData
}

var file_api_server_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_server_proto_goTypes = []any{
	(*InitServerRequest)(nil),               // 0: api_server.InitServerRequest
	(*InitServerResponse)(nil),              // 1: api_server.InitServerResponse
	(*ListServersRequest)(nil),              // 2: api_server.ListServersRequest
	(*ListServersResponse)(nil),             // 3: api_server.ListServersResponse
	(*GetServerRequest)(nil),                // 4: api_server.GetServerRequest
	(*GetServerResponse)(nil),               // 5: api_server.GetServerResponse
	(*DeleteServerRequest)(nil),             // 6: api_server.DeleteServerRequest
	(*DeleteServerResponse)(nil),            // 7: api_server.DeleteServerResponse
	(*UpdateFRPSRequest)(nil),               // 8: api_server.UpdateFRPSRequest
	(*UpdateFRPSResponse)(nil),              // 9: api_server.UpdateFRPSResponse
	(*RemoveFRPSRequest)(nil),               // 10: api_server.RemoveFRPSRequest
	(*RemoveFRPSResponse)(nil),              // 11: api_server.RemoveFRPSResponse
	(*StopFRPSRequest)(nil),                 // 12: api_server.StopFRPSRequest
	(*StopFRPSResponse)(nil),                // 13: api_server.StopFRPSResponse
	(*StartFRPSRequest)(nil),                // 14: api_server.StartFRPSRequest
	(*StartFRPSResponse)(nil),               // 15: api_server.StartFRPSResponse
	(*GetProxyStatsByServerIDRequest)(nil),  // 16: api_server.GetProxyStatsByServerIDRequest
	(*GetProxyStatsByServerIDResponse)(nil), // 17: api_server.GetProxyStatsByServerIDResponse
	(*Status)(nil),                          // 18: common.Status
	(*Server)(nil),                          // 19: common.Server
	(*ProxyInfo)(nil),                       // 20: common.ProxyInfo
}
var file_api_server_proto_depIdxs = []int32{
	18, // 0: api_server.InitServerResponse.status:type_name -> common.Status
	18, // 1: api_server.ListServersResponse.status:type_name -> common.Status
	19, // 2: api_server.ListServersResponse.servers:type_name -> common.Server
	18, // 3: api_server.GetServerResponse.status:type_name -> common.Status
	19, // 4: api_server.GetServerResponse.server:type_name -> common.Server
	18, // 5: api_server.DeleteServerResponse.status:type_name -> common.Status
	18, // 6: api_server.UpdateFRPSResponse.status:type_name -> common.Status
	18, // 7: api_server.RemoveFRPSResponse.status:type_name -> common.Status
	18, // 8: api_server.StopFRPSResponse.status:type_name -> common.Status
	18, // 9: api_server.StartFRPSResponse.status:type_name -> common.Status
	18, // 10: api_server.GetProxyStatsByServerIDResponse.status:type_name -> common.Status
	20, // 11: api_server.GetProxyStatsByServerIDResponse.proxy_infos:type_name -> common.ProxyInfo
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_server_proto_init() }
func file_api_server_proto_init() {
	if File_api_server_proto != nil {
		return
	}
	file_common_proto_init()
	file_api_server_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_server_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_server_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_server_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_server_proto_msgTypes[4].OneofWrappers = []any{}
	file_api_server_proto_msgTypes[5].OneofWrappers = []any{}
	file_api_server_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_server_proto_msgTypes[7].OneofWrappers = []any{}
	file_api_server_proto_msgTypes[8].OneofWrappers = []any{}
	file_api_server_proto_msgTypes[9].OneofWrappers = []any{}
	file_api_server_proto_msgTypes[10].OneofWrappers = []any{}
	file_api_server_proto_msgTypes[11].OneofWrappers = []any{}
	file_api_server_proto_msgTypes[12].OneofWrappers = []any{}
	file_api_server_proto_msgTypes[13].OneofWrappers = []any{}
	file_api_server_proto_msgTypes[14].OneofWrappers = []any{}
	file_api_server_proto_msgTypes[15].OneofWrappers = []any{}
	file_api_server_proto_msgTypes[16].OneofWrappers = []any{}
	file_api_server_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_server_proto_rawDesc), len(file_api_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_server_proto_goTypes,
		DependencyIndexes: file_api_server_proto_depIdxs,
		MessageInfos:      file_api_server_proto_msgTypes,
	}.Build()
	File_api_server_proto = out.File
	file_api_server_proto_goTypes = nil
	file_api_server_proto_depIdxs = nil
}
