// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api_user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_api_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{0}
}

type GetUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	UserInfo      *User                  `protobuf:"bytes,2,opt,name=user_info,json=userInfo,proto3,oneof" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_api_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserInfoResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetUserInfoResponse) GetUserInfo() *User {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type UpdateUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInfo      *User                  `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3,oneof" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserInfoRequest) Reset() {
	*x = UpdateUserInfoRequest{}
	mi := &file_api_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoRequest) ProtoMessage() {}

func (x *UpdateUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUserInfoRequest) GetUserInfo() *User {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type UpdateUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserInfoResponse) Reset() {
	*x = UpdateUserInfoResponse{}
	mi := &file_api_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoResponse) ProtoMessage() {}

func (x *UpdateUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserInfoResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetPlatformInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlatformInfoRequest) Reset() {
	*x = GetPlatformInfoRequest{}
	mi := &file_api_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlatformInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlatformInfoRequest) ProtoMessage() {}

func (x *GetPlatformInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlatformInfoRequest.ProtoReflect.Descriptor instead.
func (*GetPlatformInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{4}
}

type GetPlatformInfoResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Status                  *Status                `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	TotalClientCount        int32                  `protobuf:"varint,2,opt,name=total_client_count,json=totalClientCount,proto3" json:"total_client_count,omitempty"`
	TotalServerCount        int32                  `protobuf:"varint,3,opt,name=total_server_count,json=totalServerCount,proto3" json:"total_server_count,omitempty"`
	UnconfiguredClientCount int32                  `protobuf:"varint,4,opt,name=unconfigured_client_count,json=unconfiguredClientCount,proto3" json:"unconfigured_client_count,omitempty"`
	UnconfiguredServerCount int32                  `protobuf:"varint,5,opt,name=unconfigured_server_count,json=unconfiguredServerCount,proto3" json:"unconfigured_server_count,omitempty"`
	ConfiguredClientCount   int32                  `protobuf:"varint,6,opt,name=configured_client_count,json=configuredClientCount,proto3" json:"configured_client_count,omitempty"`
	ConfiguredServerCount   int32                  `protobuf:"varint,7,opt,name=configured_server_count,json=configuredServerCount,proto3" json:"configured_server_count,omitempty"`
	MasterRpcHost           string                 `protobuf:"bytes,8,opt,name=master_rpc_host,json=masterRpcHost,proto3" json:"master_rpc_host,omitempty"`
	MasterRpcPort           int32                  `protobuf:"varint,9,opt,name=master_rpc_port,json=masterRpcPort,proto3" json:"master_rpc_port,omitempty"`
	MasterApiPort           int32                  `protobuf:"varint,10,opt,name=master_api_port,json=masterApiPort,proto3" json:"master_api_port,omitempty"`
	MasterApiScheme         string                 `protobuf:"bytes,11,opt,name=master_api_scheme,json=masterApiScheme,proto3" json:"master_api_scheme,omitempty"`
	ClientRpcUrl            string                 `protobuf:"bytes,12,opt,name=client_rpc_url,json=clientRpcUrl,proto3" json:"client_rpc_url,omitempty"`
	ClientApiUrl            string                 `protobuf:"bytes,13,opt,name=client_api_url,json=clientApiUrl,proto3" json:"client_api_url,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GetPlatformInfoResponse) Reset() {
	*x = GetPlatformInfoResponse{}
	mi := &file_api_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlatformInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlatformInfoResponse) ProtoMessage() {}

func (x *GetPlatformInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlatformInfoResponse.ProtoReflect.Descriptor instead.
func (*GetPlatformInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetPlatformInfoResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetPlatformInfoResponse) GetTotalClientCount() int32 {
	if x != nil {
		return x.TotalClientCount
	}
	return 0
}

func (x *GetPlatformInfoResponse) GetTotalServerCount() int32 {
	if x != nil {
		return x.TotalServerCount
	}
	return 0
}

func (x *GetPlatformInfoResponse) GetUnconfiguredClientCount() int32 {
	if x != nil {
		return x.UnconfiguredClientCount
	}
	return 0
}

func (x *GetPlatformInfoResponse) GetUnconfiguredServerCount() int32 {
	if x != nil {
		return x.UnconfiguredServerCount
	}
	return 0
}

func (x *GetPlatformInfoResponse) GetConfiguredClientCount() int32 {
	if x != nil {
		return x.ConfiguredClientCount
	}
	return 0
}

func (x *GetPlatformInfoResponse) GetConfiguredServerCount() int32 {
	if x != nil {
		return x.ConfiguredServerCount
	}
	return 0
}

func (x *GetPlatformInfoResponse) GetMasterRpcHost() string {
	if x != nil {
		return x.MasterRpcHost
	}
	return ""
}

func (x *GetPlatformInfoResponse) GetMasterRpcPort() int32 {
	if x != nil {
		return x.MasterRpcPort
	}
	return 0
}

func (x *GetPlatformInfoResponse) GetMasterApiPort() int32 {
	if x != nil {
		return x.MasterApiPort
	}
	return 0
}

func (x *GetPlatformInfoResponse) GetMasterApiScheme() string {
	if x != nil {
		return x.MasterApiScheme
	}
	return ""
}

func (x *GetPlatformInfoResponse) GetClientRpcUrl() string {
	if x != nil {
		return x.ClientRpcUrl
	}
	return ""
}

func (x *GetPlatformInfoResponse) GetClientApiUrl() string {
	if x != nil {
		return x.ClientApiUrl
	}
	return ""
}

var File_api_user_proto protoreflect.FileDescriptor

const file_api_user_proto_rawDesc = "" +
	"\n" +
	"\x0eapi_user.proto\x12\bapi_user\x1a\fcommon.proto\"\x14\n" +
	"\x12GetUserInfoRequest\"\x8b\x01\n" +
	"\x13GetUserInfoResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusH\x00R\x06status\x88\x01\x01\x12.\n" +
	"\tuser_info\x18\x02 \x01(\v2\f.common.UserH\x01R\buserInfo\x88\x01\x01B\t\n" +
	"\a_statusB\f\n" +
	"\n" +
	"_user_info\"U\n" +
	"\x15UpdateUserInfoRequest\x12.\n" +
	"\tuser_info\x18\x01 \x01(\v2\f.common.UserH\x00R\buserInfo\x88\x01\x01B\f\n" +
	"\n" +
	"_user_info\"P\n" +
	"\x16UpdateUserInfoResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"\x18\n" +
	"\x16GetPlatformInfoRequest\"\x85\x05\n" +
	"\x17GetPlatformInfoResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusH\x00R\x06status\x88\x01\x01\x12,\n" +
	"\x12total_client_count\x18\x02 \x01(\x05R\x10totalClientCount\x12,\n" +
	"\x12total_server_count\x18\x03 \x01(\x05R\x10totalServerCount\x12:\n" +
	"\x19unconfigured_client_count\x18\x04 \x01(\x05R\x17unconfiguredClientCount\x12:\n" +
	"\x19unconfigured_server_count\x18\x05 \x01(\x05R\x17unconfiguredServerCount\x126\n" +
	"\x17configured_client_count\x18\x06 \x01(\x05R\x15configuredClientCount\x126\n" +
	"\x17configured_server_count\x18\a \x01(\x05R\x15configuredServerCount\x12&\n" +
	"\x0fmaster_rpc_host\x18\b \x01(\tR\rmasterRpcHost\x12&\n" +
	"\x0fmaster_rpc_port\x18\t \x01(\x05R\rmasterRpcPort\x12&\n" +
	"\x0fmaster_api_port\x18\n" +
	" \x01(\x05R\rmasterApiPort\x12*\n" +
	"\x11master_api_scheme\x18\v \x01(\tR\x0fmasterApiScheme\x12$\n" +
	"\x0eclient_rpc_url\x18\f \x01(\tR\fclientRpcUrl\x12$\n" +
	"\x0eclient_api_url\x18\r \x01(\tR\fclientApiUrlB\t\n" +
	"\a_statusB\aZ\x05../pbb\x06proto3"

var (
	file_api_user_proto_rawDescOnce sync.Once
	file_api_user_proto_rawDescData []byte
)

func file_api_user_proto_rawDescGZIP() []byte {
	file_api_user_proto_rawDescOnce.Do(func() {
		file_api_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_user_proto_rawDesc), len(file_api_user_proto_rawDesc)))
	})
	return file_api_user_proto_rawDescData
}

var file_api_user_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_user_proto_goTypes = []any{
	(*GetUserInfoRequest)(nil),      // 0: api_user.GetUserInfoRequest
	(*GetUserInfoResponse)(nil),     // 1: api_user.GetUserInfoResponse
	(*UpdateUserInfoRequest)(nil),   // 2: api_user.UpdateUserInfoRequest
	(*UpdateUserInfoResponse)(nil),  // 3: api_user.UpdateUserInfoResponse
	(*GetPlatformInfoRequest)(nil),  // 4: api_user.GetPlatformInfoRequest
	(*GetPlatformInfoResponse)(nil), // 5: api_user.GetPlatformInfoResponse
	(*Status)(nil),                  // 6: common.Status
	(*User)(nil),                    // 7: common.User
}
var file_api_user_proto_depIdxs = []int32{
	6, // 0: api_user.GetUserInfoResponse.status:type_name -> common.Status
	7, // 1: api_user.GetUserInfoResponse.user_info:type_name -> common.User
	7, // 2: api_user.UpdateUserInfoRequest.user_info:type_name -> common.User
	6, // 3: api_user.UpdateUserInfoResponse.status:type_name -> common.Status
	6, // 4: api_user.GetPlatformInfoResponse.status:type_name -> common.Status
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_user_proto_init() }
func file_api_user_proto_init() {
	if File_api_user_proto != nil {
		return
	}
	file_common_proto_init()
	file_api_user_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_user_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_user_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_user_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_user_proto_rawDesc), len(file_api_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_user_proto_goTypes,
		DependencyIndexes: file_api_user_proto_depIdxs,
		MessageInfos:      file_api_user_proto_msgTypes,
	}.Build()
	File_api_user_proto = out.File
	file_api_user_proto_goTypes = nil
	file_api_user_proto_depIdxs = nil
}
